apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.openshift.io/serving-cert-secret-name: sfa-worker-api-svc-cert
  labels:
    app: sfa-api
  name: sfa-worker-api
  namespace: {{ namespace }}
spec:
  ports:
  - name: 8080-tcp
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    deploymentconfig: sfa-worker-api
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
